INSERT INTO  TB_CLIENTE(NOME, CPF, EMAIL, TELEFONE) VALUES("TESTE", "123.456.789-10", "example@example.com", "(11) 12345-6789");
INSERT INTO TB_ENDERECO(ID_CLIENTE, LOGRADOURO, BAIRRO, COMPLEMENTO) VALUES(1, "Rua Teste", "Bairro Teste", "apto 1 bloco 1");

INSERT INTO TB_PRODUTO(DESCRICAO, VALOR_UNITARIO) VALUES("NOTEBOOK", 2000.00);
INSERT INTO TB_ESTOQUE(ID_PRODUTO, QUANTIDADE) VALUES(1, 500);

INSERT INTO TB_STATUS(DESCRICAO) VALUES("AGUARDANDO PAGAMENTO");